/** @type {import('tailwindcss').Config} */
import { colors, typography, spacing, borderRadius, shadows, animations } from './src/styles/design-tokens.js';

export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: colors.primary,
        secondary: colors.secondary,
        success: colors.success,
        warning: colors.warning,
        error: colors.error,
        neutral: colors.neutral,
        semantic: colors.semantic,
        accent: colors.accent,
      },
      backgroundImage: {
        'gradient-primary': colors.gradients.primary.light,
        'gradient-primary-dark': colors.gradients.primary.dark,
        'gradient-primary-hover': colors.gradients.primary.hover,
        'gradient-secondary': colors.gradients.secondary.light,
        'gradient-secondary-dark': colors.gradients.secondary.dark,
        'gradient-success': colors.gradients.success.light,
        'gradient-success-dark': colors.gradients.success.dark,
        'gradient-warning': colors.gradients.warning.light,
        'gradient-warning-dark': colors.gradients.warning.dark,
        'gradient-error': colors.gradients.error.light,
        'gradient-error-dark': colors.gradients.error.dark,
        'gradient-accent-purple': colors.gradients.accent.purple,
        'gradient-accent-cyan': colors.gradients.accent.cyan,
        'gradient-accent-pink': colors.gradients.accent.pink,
        'gradient-accent-vibrant': colors.gradients.accent.vibrant,
        'gradient-background-light': colors.gradients.background.light,
        'gradient-background-dark': colors.gradients.background.dark,
        'gradient-background-subtle': colors.gradients.background.subtle,
      },
      fontFamily: typography.fontFamily,
      fontSize: typography.fontSize,
      fontWeight: typography.fontWeight,
      spacing: spacing,
      borderRadius: borderRadius,
      boxShadow: {
        ...shadows,
        'glow-primary': shadows.glow.primary,
        'glow-secondary': shadows.glow.secondary,
        'glow-success': shadows.glow.success,
        'glow-warning': shadows.glow.warning,
        'glow-error': shadows.glow.error,
        'glow-purple': shadows.glow.purple,
        'glow-cyan': shadows.glow.cyan,
        'glow-pink': shadows.glow.pink,
        'elevated-sm': shadows.elevated.sm,
        'elevated-md': shadows.elevated.md,
        'elevated-lg': shadows.elevated.lg,
        'depth-sm': shadows.depth.sm,
        'depth-md': shadows.depth.md,
        'depth-lg': shadows.depth.lg,
        'depth-xl': shadows.depth.xl,
      },
      transitionDuration: {
        ...animations.duration,
      },
      transitionTimingFunction: {
        ...animations.easing,
      },
      zIndex: {
        dropdown: 1000,
        sticky: 1020,
        fixed: 1030,
        'modal-backdrop': 1040,
        modal: 1050,
        popover: 1060,
        tooltip: 1070,
        toast: 1080,
      },
      animation: {
        'fade-in': 'fade-in 0.3s ease-in',
        'scale-in': 'scale-in 0.2s ease-out',
        'slide-in-right': 'slide-in-right 0.3s ease-out',
        'slide-in-left': 'slide-in-left 0.3s ease-out',
        'slide-up': 'slide-up 0.3s ease-out',
        'slide-down': 'slide-down 0.3s ease-out',
        'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'gradient-shift': 'gradient-shift 3s ease infinite',
        'glow-pulse': 'glow-pulse 2s ease-in-out infinite',
        'float': 'float 6s ease-in-out infinite',
        'shimmer': 'shimmer 2s linear infinite',
      },
      keyframes: {
        'fade-in': {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        'scale-in': {
          '0%': { opacity: '0', transform: 'scale(0.95)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        'slide-in-right': {
          '0%': { opacity: '0', transform: 'translateX(100%)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        'slide-in-left': {
          '0%': { opacity: '0', transform: 'translateX(-100%)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        'slide-up': {
          '0%': { opacity: '0', transform: 'translateY(10px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'slide-down': {
          '0%': { opacity: '0', transform: 'translateY(-10px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'gradient-shift': {
          '0%, 100%': { backgroundPosition: '0% 50%' },
          '50%': { backgroundPosition: '100% 50%' },
        },
        'glow-pulse': {
          '0%, 100%': { opacity: '1', filter: 'brightness(1)' },
          '50%': { opacity: '0.8', filter: 'brightness(1.2)' },
        },
        'float': {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-10px)' },
        },
        'shimmer': {
          '0%': { backgroundPosition: '-1000px 0' },
          '100%': { backgroundPosition: '1000px 0' },
        },
      },
    },
  },
  plugins: [],
}
